### ISSUE TITLE
Attempt to index a nil value

### ISSUE THREAD

**Issue by lfdominguez** [arkav/lualine-lsp-progress#3]
Hi i have this error message on nvim, using rust-tools (rust_analyzer):

`Error executing vim.schedule lua callback: ...ine-lsp-progress/lua/lualine/components/lsp_progress.lua:135: attempt to index a nil value`

https://github.com/arkav/lualine-lsp-progress/blob/4d7c4e5cc7dc100280d66e240f670f40bdf601c9/lua/lualine/components/lsp_progress.lua#L135

**Comment by garrickwelsh** [comment]
Thanks @lfdominguez, I have created a pull request with a guard clause, that should prevent this issue (caused by a race condition). Cheers, Garrick.

**Comment by lfdominguez** [comment]
Great, thanks to you.. I tested the PR and is working great.

**Comment by arkav** [comment]
Fix merged #4.
