### ISSUE TITLE
Doesn't work with latest nightly

### ISSUE THREAD

**Issue by Mte90** [arkav/lualine-lsp-progress#8]
There is this fork with the fix https://github.com/clason/lualine-lsp-progress/
With that fork I am getting this error and lualine doesn't work:

![immagine](https://user-images.githubusercontent.com/403283/139271470-79611989-f46b-4a91-bd53-85bd881acf4f.png)

**Comment by arkav** [comment]
Hi, it appears your using an outdated version of this plugin, make sure your either using the master branch or the adapt-shadman branch of clason's fork.

**Comment by Mte90** [comment]
Thanks for the help, that fork doesn't have issues and in the readme there isn't any info about this branch
